name: goreleaser

on:
  create:

jobs:
  goreleaser:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Install ceph
        run: |
          wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
          echo "deb https://download.ceph.com/debian-pacific/ ${VERSION_CODENAME} main" | sudo tee /etc/apt/sources.list.d/ceph.list
          sudo apt-get update
          sudo apt-get install -y libcephfs-dev librbd-dev librados-dev
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
